#!/bin/bash

set -x
set -e

SRCS="start.S main.c intc.c uart.c exceptions.S"
CFLAGS="-O2 -ffreestanding -nostdlib -Wall -mcpu=68040"

m68k-elf-gcc ${CFLAGS} -Ttext=0 ${SRCS} -o m68k
m68k-elf-objdump -D m68k | tee m68k.lst
qemu-system-m68k --machine virt -cpu m68040 -kernel m68k -serial mon:stdio -nographic \
    -trace goldfish_pic_read -trace goldfish_pic_write \
    -d int

