#!/bin/bash

set -x
set -e

SRCS="start.S main.c goldfish_tty.c"

m68k-elf-gcc -flto -O2 -ffreestanding -nostdlib -Ttext=0 ${SRCS} -o m68k
m68k-elf-objdump -d m68k
qemu-system-m68k --machine virt -cpu m68040 -kernel m68k -serial mon:stdio -nographic

