#!/bin/bash

set -x
set -e

m68k-elf-gcc -O2 -ffreestanding -nostdlib -Ttext=0x40000000 start.S main.c -o m68k
m68k-elf-objdump -d m68k
qemu-system-m68k --machine mcf5208evb -cpu m68030 -kernel m68k -serial mon:stdio -nographic

